### ISSUE TITLE
sourceweb failing to build on OS X 10.9 (w/ Qt 4.8.6)

### ISSUE THREAD

**Issue by lichuang** [rprichard/sourceweb#4]
clang++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-reserved-user-defined-literal -fPIC -pthread -fvisibility-inlines-hidden -fno-rtti -fno-exceptions -g -gdwarf-2 -arch x86_64 -Wall -W -Wno-unused-parameter -Wno-uninitialized -Wno-unused-parameter -Wno-strict-aliasing -DJSON_IS_AMALGAMATION -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DINDEXER_CLANG_DIR=/Users/lichuang/source/clang+llvm-3.4.1-x86_64-apple-darwin10.9 -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Qt4.8/mkspecs/unsupported/macx-clang -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/usr/include -I../libindexdb -I../third_party/libjsoncpp -I../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include -I. -F/Library/Frameworks -o ASTIndexer.o ASTIndexer.cc
ASTIndexer.cc:272:12: error: no member named 'getParenRange' in 'clang::CXXConstructExpr'
    if (e->getParenRange().isValid()) {
        ~  ^
ASTIndexer.cc:291:24: error: no member named 'getParenRange' in 'clang::CXXConstructExpr'
                    e->getParenRange().getEnd(),
                    ~  ^
In file included from ASTIndexer.cc:1:
In file included from ./ASTIndexer.h:6:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/RecursiveASTVisitor.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/Decl.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/APValue.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/Basic/LLVM.h:22:
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:55:16: error: no member named 'classof' in 'clang::TagTypeLoc'
    return To::classof(&Val);
           ~~~~^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:77:32: note: in instantiation of member function 'llvm::isa_impl<clang::TagTypeLoc, clang::TypeLoc,
      void>::doit' requested here
    return isa_impl<To, From>::doit(Val);
                               ^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:124:36: note: in instantiation of member function 'llvm::isa_impl_cl<clang::TagTypeLoc, const
      clang::TypeLoc>::doit' requested here
    return isa_impl_cl<To,FromTy>::doit(Val);
                                   ^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:136:70: note: in instantiation of member function 'llvm::isa_impl_wrap<clang::TagTypeLoc, const
      clang::TypeLoc, const clang::TypeLoc>::doit' requested here
                       typename simplify_type<const Y>::SimpleType>::doit(Val);
                                                                     ^
ASTIndexer.cc:584:15: note: in instantiation of function template specialization 'llvm::isa<clang::TagTypeLoc, clang::TypeLoc>' requested here
    if (llvm::isa<clang::TagTypeLoc>(tl)) {
              ^
In file included from ASTIndexer.cc:1:
In file included from ./ASTIndexer.h:6:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/RecursiveASTVisitor.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/Decl.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/APValue.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/Basic/LLVM.h:22:
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:55:16: error: no member named 'classof' in 'clang::TypedefTypeLoc'
    return To::classof(&Val);
           ~~~~^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:77:32: note: in instantiation of member function 'llvm::isa_impl<clang::TypedefTypeLoc, clang::TypeLoc,
      void>::doit' requested here
    return isa_impl<To, From>::doit(Val);
                               ^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:124:36: note: in instantiation of member function 'llvm::isa_impl_cl<clang::TypedefTypeLoc, const
      clang::TypeLoc>::doit' requested here
    return isa_impl_cl<To,FromTy>::doit(Val);
                                   ^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:136:70: note: in instantiation of member function 'llvm::isa_impl_wrap<clang::TypedefTypeLoc, const
      clang::TypeLoc, const clang::TypeLoc>::doit' requested here
                       typename simplify_type<const Y>::SimpleType>::doit(Val);
                                                                     ^
ASTIndexer.cc:589:22: note: in instantiation of function template specialization 'llvm::isa<clang::TypedefTypeLoc, clang::TypeLoc>' requested here
    } else if (llvm::isa<clang::TypedefTypeLoc>(tl)) {
                     ^
In file included from ASTIndexer.cc:1:
In file included from ./ASTIndexer.h:6:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/RecursiveASTVisitor.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/Decl.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/APValue.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/Basic/LLVM.h:22:
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:55:16: error: no member named 'classof' in 'clang::TemplateTypeParmTypeLoc'
    return To::classof(&Val);
           ~~~~^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:77:32: note: in instantiation of member function 'llvm::isa_impl<clang::TemplateTypeParmTypeLoc,
      clang::TypeLoc, void>::doit' requested here
    return isa_impl<To, From>::doit(Val);
                               ^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:124:36: note: in instantiation of member function 'llvm::isa_impl_cl<clang::TemplateTypeParmTypeLoc, const
      clang::TypeLoc>::doit' requested here
    return isa_impl_cl<To,FromTy>::doit(Val);
                                   ^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:136:70: note: in instantiation of member function 'llvm::isa_impl_wrap<clang::TemplateTypeParmTypeLoc, const
      clang::TypeLoc, const clang::TypeLoc>::doit' requested here
                       typename simplify_type<const Y>::SimpleType>::doit(Val);
                                                                     ^
ASTIndexer.cc:594:22: note: in instantiation of function template specialization 'llvm::isa<clang::TemplateTypeParmTypeLoc, clang::TypeLoc>' requested here
    } else if (llvm::isa<clang::TemplateTypeParmTypeLoc>(tl)) {
                     ^
In file included from ASTIndexer.cc:1:
In file included from ./ASTIndexer.h:6:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/RecursiveASTVisitor.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/Decl.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/AST/APValue.h:17:
In file included from ../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/clang/Basic/LLVM.h:22:
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:55:16: error: no member named 'classof' in 'clang::TemplateSpecializationTypeLoc'
    return To::classof(&Val);
           ~~~~^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:77:32: note: in instantiation of member function 'llvm::isa_impl<clang::TemplateSpecializationTypeLoc,
      clang::TypeLoc, void>::doit' requested here
    return isa_impl<To, From>::doit(Val);
                               ^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:124:36: note: in instantiation of member function 'llvm::isa_impl_cl<clang::TemplateSpecializationTypeLoc,
      const clang::TypeLoc>::doit' requested here
    return isa_impl_cl<To,FromTy>::doit(Val);
                                   ^
../../clang+llvm-3.4.1-x86_64-apple-darwin10.9/include/llvm/Support/Casting.h:136:70: note: in instantiation of member function 'llvm::isa_impl_wrap<clang::TemplateSpecializationTypeLoc,
      const clang::TypeLoc, const clang::TypeLoc>::doit' requested here
                       typename simplify_type<const Y>::SimpleType>::doit(Val);
                                                                     ^
ASTIndexer.cc:599:22: note: in instantiation of function template specialization 'llvm::isa<clang::TemplateSpecializationTypeLoc, clang::TypeLoc>' requested here
    } else if (llvm::isa<clang::TemplateSpecializationTypeLoc>(tl)) {
                     ^
6 errors generated.
make[1]: *** [ASTIndexer.o] Error 1



lichuangdeMac-mini:sourceweb lichuang$ clang++ --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.2.0
Thread model: posix

clang lib version:
./configure --with-clang-dir=/Users/lichuang/source/clang+llvm-3.4.1-x86_64-apple-darwin10.9

**Comment by rprichard** [comment]
SourceWeb uses Clang's libraries, which are not stable between releases.  At the time this bug was filed, SourceWeb required Clang 3.2, but you tried to use Clang 3.4.  As of now, SourceWeb uses Clang 3.5.  (I haven't tried building it against Clang 3.4, so I don't know whether it would work.)
