### ISSUE TITLE
sourceweb failing to build on OS X 10.8.5 (w/ Qt 5.1.1)

### ISSUE THREAD

**Issue by yan** [rprichard/sourceweb#3]
Grabbed the prerequisite as described in the README, tried building after installing Qt 5.1.1, received the following errors while building:

```
In file included from ASTIndexer.cc:1:
In file included from ./ASTIndexer.h:6:
In file included from ../../../clang-3.2-1-x86_64-darwin/include/clang/AST/RecursiveASTVisitor.h:17:
In file included from ../../../clang-3.2-1-x86_64-darwin/include/clang/AST/Decl.h:17:
In file included from ../../../clang-3.2-1-x86_64-darwin/include/clang/AST/APValue.h:18:
In file included from ../../../clang-3.2-1-x86_64-darwin/include/llvm/ADT/APSInt.h:18:
In file included from ../../../clang-3.2-1-x86_64-darwin/include/llvm/ADT/APInt.h:18:
In file included from ../../../clang-3.2-1-x86_64-darwin/include/llvm/ADT/ArrayRef.h:13:
In file included from ../../../clang-3.2-1-x86_64-darwin/include/llvm/ADT/SmallVector.h:17:
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:90:1: error: 'alignas' attribute cannot be applied to types
LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT(1);
^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:79:10: note: expanded from macro 'LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT'
    char alignas(x) aligned; \
         ^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:91:1: error: 'alignas' attribute cannot be applied to types
LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT(2);
^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:79:10: note: expanded from macro 'LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT'
    char alignas(x) aligned; \
         ^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:92:1: error: 'alignas' attribute cannot be applied to types
LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT(4);
^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:79:10: note: expanded from macro 'LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT'
    char alignas(x) aligned; \
         ^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:93:1: error: 'alignas' attribute cannot be applied to types

...

../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:101:1: error: 'alignas' attribute cannot be applied to types
LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT(4096);
^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:79:10: note: expanded from macro 'LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT'
    char alignas(x) aligned; \
         ^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:102:1: error: 'alignas' attribute cannot be applied to types
LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT(8192);
^
../../../clang-3.2-1-x86_64-darwin/include/llvm/Support/AlignOf.h:79:10: note: expanded from macro 'LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT'
    char alignas(x) aligned; \
         ^
13 errors generated.
make[1]: *** [ASTIndexer.o] Error 1
make: *** [sub-clang-indexer-make_first-ordered] Error 2

```

**Comment by rprichard** [comment]
I've updated SourceWeb (with help from @adytzu2007) to use Clang 3.5 instead of Clang 3.2, which fixes the OS X build problem.  I verified that SourceWeb builds with OS X 10.10.2 and Qt 5.4, though it will very probably work versions of OS X newer than 4.7 and Qt 4.6 or later.  (e.g. It also works with HomeBrew Qt 4.8.6.)

See [this link](https://github.com/rprichard/sourceweb/issues/2#issuecomment-90806128) for details.
